default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

laptop:
    <<: *default 
    database: utdebatecamp_com_development
    username: cecilgol
    host: localhost
    port: 5432
    min_messages: notice

development:
  <<: *default
  database: utdebatecamp_com_development
  username: cecilgol 
  host: aphrodite.local
  port: 5432
  min_messages: notice

test:
  <<: *default
  database: utdebatecamp_com_test
  host: aphrodite.local
  port: 5432
  min_messages: notice

production:
  <<: *default
  database: utdebatecamp_com_production
  username: utdebatecamp_com
  password: <%= ENV['UTDEBATECAMP_COM_DATABASE_PASSWORD'] %>
