default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: utdebatecamp_com_development
  username: utdebatecamp_com
  password: very secure password
  host: localhost
  port: 5432

test:
  <<: *default
  database: utdebatecamp_com_test
  username: utdebatecamp_com
  password: very secure password
  host: localhost
  port: 5432

production:
  <<: *default
  database: utdebatecamp_com_production
  username: utdebatecamp_com
  password: <%= ENV['UTDEBATECAMP_COM_DATABASE_PASSWORD'] %>
